### ISSUE TITLE
Add change log to documentation

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-testing#23]
Incorporate a clear and detailed change log to assist the community in detecting and applying change

**Comment by elizabetharnold** [comment]
Change Control has been introduced to Log the details of changes to the documentation over time and to make the file available from within the CDR Test Documentation.

The CDR Test Documentation Change Log will be available via a link in the introduction section of the document.

The following table is a _**sample**_ of the change log for v1.0.1, dates subject to change:

Change   date | Version | Identifier | Field/s | Change | [GitHub Issue #](https://github.com/ConsumerDataStandardsAustralia/standards-testing/issues)
-- | -- | -- | -- | -- | --
19/05/2022 | 1.0.0 | N/A | All | Initial draft of CDR Test   Documentation covering Scenarios, Test Cases and Assertions for Energy   Standing Data, Usage and DER in Suite.010 for Data Recipient calls to Data   Holders and Suite.011 for Data Holder calls to the Secondary Data Holder | N/A
3/06/2022 | 1.0.1 | T.EAS.003 | Title | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAS.006 | Title | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAS.011 | Title | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAS.021 | Title | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAS.028 | Title | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAS.033 | Title | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAS.069 | Title; PreConditions | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAS.070 | Title; PreConditions | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAS.071 | Title; PreConditions | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAS.072 | Title; PreConditions | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAS.073 | Title; PreConditions | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAS.074 | Title; PreConditions | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.003 | Title | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.007 | Title | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.013 | Title | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.024 | Title | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.034 | Title | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.040 | Title | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.047 | Title | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.062 | Title | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.125 | Title; PreConditions | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.126 | Title; PreConditions | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.128 | Title; PreConditions | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.129 | Title; PreConditions | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.130 | Title; PreConditions | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.131 | Title; PreConditions | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | T.EAR.132 | Title; PreConditions | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | A.CVN.004 | Title; Given Change | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | A.CVN.005 | Title; Given Change | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | A.CVM.001 | Title; Given; When; Then | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | A.CVM.002 | Title; Given | x-v-min corrected to x-min-v | 20
3/06/2022 | 1.0.1 | S.EAR.073 | Test Scenarios | Get Service Points changed to Get Service Points v1 | 22
3/06/2022 | 1.0.1 | S.EAR.074 | Test Scenarios | Get Service Points Negative changed to Get Service Points   Negative v1 | 22
3/06/2022 | 1.0.1 | S.EAR.075 | Test Scenarios | Get Service Point Detail changed to Get Service Point Detail   v1 | 22
3/06/2022 | 1.0.1 | S.EAR.076 | Test Scenarios | Get Service Point Detail Negative changed to Get Service Point   Detail Negative v1 | 22
3/06/2022 | 1.0.1 | S.EAR.077 | Test Scenarios | Get Usage For Service Point changed to Get Usage For Service   Point v1 | 22
3/06/2022 | 1.0.1 | S.EAR.078 | Test Scenarios | Get Usage For Service Point Negative changed to Get Usage For   Service Point Negative v1 | 22
3/06/2022 | 1.0.1 | S.EAR.079 | Test Scenarios | Get Bulk Usage changed to Get Bulk Usage v1 | 22
3/06/2022 | 1.0.1 | S.EAR.080 | Test Scenarios | Get Bulk Usage Negative changed to Get Bulk Usage Negative v1 | 22
3/06/2022 | 1.0.1 | S.EAR.081 | Test Scenarios | Get Usage For Specific Service Points changed to Get Usage For   Specific Service Points v1 | 22
3/06/2022 | 1.0.1 | S.EAR.082 | Test Scenarios | Get Usage For Specific Service Points Negative changed to Get   Usage For Specific Service Points Negative v1 | 22
3/06/2022 | 1.0.1 | S.EAR.083 | Test Scenarios | Get DER for Service Point changed to Get DER for Service Point   v1 | 22
3/06/2022 | 1.0.1 | S.EAR.084 | Test Scenarios | Get DER for Service Point Negative changed to Get DER for   Service Point Negative v1 | 22
3/06/2022 | 1.0.1 | S.EAR.085 | Test Scenarios | Get Bulk DER changed to Get Bulk DER v1 | 22
3/06/2022 | 1.0.1 | S.EAR.086 | Test Scenarios | Get Bulk DER Negative changed to Get Bulk DER Negative v1 | 22
3/06/2022 | 1.0.1 | S.EAR.087 | Test Scenarios | Get DER For Specific Service Points changed to Get DER For   Specific Service Points v1 | 22
3/06/2022 | 1.0.1 | S.EAR.088 | Test Scenarios | Get DER For Specific Service Points Negative changed to Get   DER For Specific Service Points Negative v1 | 22
3/06/2022 | 1.0.1 | S.EAS.089 | Test Scenarios | Get Service Points SR changed to Get Service Points SR v1 | 22
3/06/2022 | 1.0.1 | S.EAS.090 | Test Scenarios | Get Service Points Negative SR changed to Get Service Points   Negative SR v1 | 22
3/06/2022 | 1.0.1 | S.EAS.091 | Test Scenarios | Get Service Point Detail SR changed to Get Service Point   Detail SR v1 | 22
3/06/2022 | 1.0.1 | S.EAS.092 | Test Scenarios | Get Service Point Detail Negative SR changed to Get Service   Point Detail Negative SR v1 | 22
3/06/2022 | 1.0.1 | S.EAS.093 | Test Scenarios | Get Usage For Service Point SR changed to Get Usage For   Service Point SR v1 | 22
3/06/2022 | 1.0.1 | S.EAS.094 | Test Scenarios | Get Usage For Service Point Negative SR changed to Get Usage   For Service Point Negative SR v1 | 22
3/06/2022 | 1.0.1 | S.EAS.095 | Test Scenarios | Get Usage For Specific Service Points SR changed to Get Usage   For Specific Service Points SR v1 | 22
3/06/2022 | 1.0.1 | S.EAS.096 | Test Scenarios | Get Usage For Specific Service Points Negative SR changed to   Get Usage For Specific Service Points Negative SR v1 | 22
3/06/2022 | 1.0.1 | S.EAS.097 | Test Scenarios | Get DER for Service Point SR changed to Get DER for Service   Point SR v1 | 22
3/06/2022 | 1.0.1 | S.EAS.098 | Test Scenarios | Get DER for Service Point Negative SR changed to Get DER for   Service Point Negative SR v1 | 22
3/06/2022 | 1.0.1 | S.EAS.099 | Test Scenarios | Get DER For Specific Service Points SR changed to Get DER For   Specific Service Points SR v1 | 22
3/06/2022 | 1.0.1 | S.EAS.100 | Test Scenarios | Get DER For Specific Service Points Negative SR changed to Get   DER For Specific Service Points Negative SR v1 | 22
3/06/2022 | 1.0.1 | N/A | Change Log | Introduced Change Control to Log   the details of changes to the documentation over time and make the file   available from within the CDR  Test   Documentation | 23

**Comment by tom-schier** [comment]
Change log added as xls file. Merged and committed
