### ISSUE TITLE
Assertion A.CPG.001 is missing from Suite.010 Test Cases 

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-testing#24]
**Description**
Some Test Cases for APIs that support pagination in Suite.010 Test Cases are missing A.CPG.001 where Happy Path = TRUE  for ' - with pagination' tests.

**Related Work Items**
    - None

**Comment by elizabetharnold** [comment]
Assertion A.CPG.001 added to T.EAR.002, T.EAR.012, T.EAR.023. T.EAR.039 and T.EAR.046

**Comment by tom-schier** [comment]
Merged and published
