### ISSUE TITLE
Assertion A.CFC.001 is missing from Test Case T.EAR.61

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-testing#25]
**Description**
Assertion A.CFC.001 is missing from Test Case T.EAR.61

**Related Work Items**
    - None

**Comment by elizabetharnold** [comment]
A.CFC.001 has been added to Test Case T.EAR.61 in source data

**Comment by tom-schier** [comment]
Merged and published
