### ISSUE TITLE
Reframe the Given When Then statements for a number of assertions

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-testing#26]
**Description**
Currently the assertion looks like this:
 
![image](https://user-images.githubusercontent.com/94343290/174513244-f328fc6e-1768-4ad1-a924-3cafb51b3345.png)

It should look something like this: 
 
![image](https://user-images.githubusercontent.com/94343290/174513253-58ae9bd0-4313-48f7-9d71-e3d1daf3dd69.png)

Reasoning:
The current interpretation you could have a valid x-fapi-customer-ip-address but the assertion could still fail as it tests for a 200 response code. So, you could have a scenario where you get a 4xx return code (e.g. something wrong x-v), and this particular assertion would fail.
However, the intention of this assertion is to evaluate x-fapi-customer-ip-address

There are other examples of this, a review of all assertions is required.

**Related Work Items**
    - none

**Comment by elizabetharnold** [comment]
Resolving this issue has resulted in wholesale change to the way the GIVEN WHEN THEN statements are written for the majority of the existing Assertions.  They now conform better to the Business Driven Development methodology where the WHEN statement has been converted to an action rather than additional preconditions which have been consolidated in the GIVEN statement.  The THEN statements all contain the outcome that can be asserted once the test has been executed.  

While this creates significant change the context of each assertion remains the same, it is just expressed in a different way.  Full details of changes made to each Assertion can be found in the Change Log for v1.0.2 when it's published at https://consumerdatastandardsaustralia.github.io/standards-testing/latest/. 

Thanks to @tom-schier for identifying the inconsistencies and your work to resolve this issue.

**Comment by tom-schier** [comment]
This has been resolved with release 1.0.2
