### ISSUE TITLE
Test case is showing as Negative when it's Positive

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-testing#31]
**Description**
The source data shows the test case is Positive (Happy Path = TRUE) however the value is incorrectly converted to Negative when displayed in the documentation.
![image](https://user-images.githubusercontent.com/94343290/179435579-2e0e52a7-886e-4019-8c08-53c93c098f17.png)

**Related Work Items**
None

**Comment by tom-schier** [comment]
This has been resolved with release 1.0.2
