### ISSUE TITLE
Multiple GIVEN statements not breaking onto new line

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-testing#32]
**Description**
Each Condition in the GIVEN statement separated by 'AND' should appear on a new line.  When there is more than 2 conditions this is not occurring.  
![image](https://user-images.githubusercontent.com/94343290/179436966-fac91d2d-6ff1-4462-9919-e02a7d0b9519.png)

**Related Work Items**
Where applicable please supply a list of related work items (using #issue format):
    - #1

**Comment by tom-schier** [comment]
This has been resolved with release 1.0.2
