### ISSUE TITLE
Publish Test Cases and Assertions for Suite.008 APIs - Energy Accounts

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-testing#33]
- Draft Test Cases and Assertions for "Suite.008 APIs - Energy Accounts" for internal review
- Resolve any errors or omissions 
- Update change log
- Publish to an new version of CDR Test Documentation

**Comment by elizabetharnold** [comment]
Test Cases have been written and reviewed, they are ready to be published in v1.0.3

**Comment by tom-schier** [comment]
These have been published with 1.0.3
