### ISSUE TITLE
Publish Test Cases and Assertions for Suite.005 APIs - Common Admin

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-testing#35]
- Draft Test Cases and Assertions for "Suite.005 APIs - Common Admin" for internal review
- Resolve any errors or omissions
- Update change log
- Publish to an new version of CDR Test Documentation

**Comment by elizabetharnold** [comment]
Test cases have been written and are waiting for review.  If reviewed and no changes are required they can be published in 1.0.3

**Comment by tom-schier** [comment]
These have been published with 1.0.3
