### ISSUE TITLE
PreCondition in T.EAR.008 is incomplete add 'Invalid' 

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-testing#38]
Add 'invalid' to finish sentence in PreCondition and remove <> from servicePointId, only {} are required.

![image](https://user-images.githubusercontent.com/94343290/182747372-ac4e6c8d-3201-4970-975d-815b57708e26.png)

**Comment by elizabetharnold** [comment]
The source document has been updated and the change can be included in the next release.

**Comment by tom-schier** [comment]
This was released with 1.0.3 and is now "latest"
