### ISSUE TITLE
testdata - Add support for user authentication data

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards-testing#41]
**Description**
Need to add support to testdata for user authentication data.  This would include:
* Add support for users for authentication
* Add support for secondary user instructions
* Add support for nominated representatives

**Comment by sumayahasancds** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[standards-testing]: testdata - Add support for user authentication data](https://trello.com/c/UzswOZWT/19-standards-testing-testdata-add-support-for-user-authentication-data)
