### ISSUE TITLE
Suite.010 and .011 are missing tests for invalid minimum version format 

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-testing#49]
Suite.010 and .011 are missing tests for invalid minimum version format, each API in the suite needs to have a negative test added to ensure the invalid format generates the correct error (A.CVM.002).

**Comment by elizabetharnold** [comment]
These tests have been added to the source data and can be published in v1.0.3

**Comment by tom-schier** [comment]
These have been added with the 1.0.3 release and are now "latest"
