### ISSUE TITLE
Inconsistent formatting in the Assertion predicate details

### ISSUE THREAD

**Issue by tom-schier** [ConsumerDataStandardsAustralia/standards-testing#5]
Currently the values under “When” and “Then” have different formatting rules, the latter is using brackets.
All formatting in the Html should be as it currently is for the “When”.

![InconsistentFormatting](https://user-images.githubusercontent.com/19284769/165237222-d67f12a3-5f00-4c7c-8e50-2520fcdb7d2b.JPG)

**Comment by elizabetharnold** [comment]
@tom-schier I agree with your comment that "All formatting in the Html should be as it currently is for the 'When'”.  However in this case Issue [#26](https://github.com/ConsumerDataStandardsAustralia/standards-testing/issues/26) changed the content as shown below and 'When' in your comment should now read as 'Given'. 
![image](https://user-images.githubusercontent.com/94343290/181408478-1816281b-a17e-41fd-9948-135635ac992c.png)
For natural language it does not make sense to read the Then statement in the example as 'Then AND the response...'.  The formatting once updated should display this example as:

Then the response has a status of 400
AND the response body has ErrorListResponse object
AND error code is "Header/invalid"

**Comment by tom-schier** [comment]
These have been published with 1.0.3
