### ISSUE TITLE
Remove Assertions A.CFA.001, A.CFC.001, A.CCH.001 and A.CAI.001 and delete from all Test Cases

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-testing#51]
Following a detailed review of these assertions the DSB has decided to remove them to avoid confusion.  Other assertions deal with those circumstances where the header attributes are missing or malformed.

Remove Assertions A.CFA.001, A.CFC.001, A.CCH.001 and A.CAI.001 and delete from all Test Cases

**Comment by sumayahasancds** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[standards-testing]: Remove Assertions A.CFA.001, A.CFC.001, A.CCH.001 and A.CAI.001 and delete from all Test Cases](https://trello.com/c/nU3f64cx/13-standards-testing-remove-assertions-acfa001-acfc001-acch001-and-acai001-and-delete-from-all-test-cases)
