### ISSUE TITLE
Inconsistent allocation of alpha characters in numbering convention

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-testing#57]
**Description**
The [Numbering Convention](https://github.com/ConsumerDataStandardsAustralia/standards-testing#numbering-convention) described for the CDR Test Documentation allocates alpha characters to specific **Suites** and **Assertions**.  The general rule is Suite specific Test Cases and Assertions inherit three alpha characters assigned to the Scenario they belong to for grouping purposes. Additionally the Character 'C' has been reserved for Common assertions because each assertion is named based on the field name being tested. 

To automate the sequential allocation of numbers to the Scenario, Test Case and Assertion hierarchy, this logic is contradicted because **Scenarios** for Common APIs, i.e. Admin (error as documentation suggests this character should be A) and Customer, have been allocated alpha character C.  This character naturally flows on to Test Cases and Assertions where the three alpha characters are appended with sequential numbers as each test case or assertion is added.  However, Suite specific assertions have the potential to repeat numbered Common assertions which also start with the character C.  

Options
To ensure the numbering convention remains unique one of the following options needs to be considered. 

1. Common Suites have the character C reassigned to another alpha, meaning the scenario, test case and assertion identifiers published for Suite.005 - Common Admin and Suite.006 - Common Customer will need to be reallocated.
2. Common Assertions have the current convention of naming based on Common plus meaningful field names reallocated to a sequentially order character set and to reallocate the identifiers.
3. Automated numbering routines take this anomaly into consideration by creating exceptions to the rule.
4. Create a Suite for Common Assertions to assign the three alphas so they can't be used by any other suite

**Related Work Items**
None

**Comment by CDR-API-Stream** [comment]
This issue will be resolve when DSB deploys a new version of the CDR Test Documentation (anticipated to be v2.0.0).  Details of the solution will added to this ticket when it's closed.

**Comment by elizabetharnold** [comment]
To address this issue the following changes have been made and will be published in v2.0.0.

- Suites have had numbers replaced with the corresponding alpha characters that are already assigned to Scenarios, Test Cases and Assertions, e.g. SUITE.008 is now SUITE.EAA
- Scenarios, Test Cases and Assertions have all had numeric characters increased from 3 to 4, e.g. S.EAA.001, T.EAA.001 and A.EAA.001 are all now S.EAA.0001, T.EAA.0001 and A.EAA.0001 
- Common Assertions are now known as Global Assertions and have had alpha characters such as CMN, CPG etc replaced with ZAA, numbers are now sequentially allocated and all test cases linked to the global assertions are now linked to the new identifier.

Full details of the changes can be found in the change log linked from the introduction text when v2.0.0 is published.

The information banner alerting site visitors of these changes should also be deleted.
